### ISSUE TITLE
RTD build fails with module not found `sphinxcontrib.cadquery`

### ISSUE THREAD

**Issue by sethfischer** [sethfischer/sphinxcontrib-cadquery#42]
_Read the Docs_ build fails with `ModuleNotFoundError: No module named 'sphinxcontrib.cadquery'`:

```
python -m sphinx -T -E -b html -d _build/doctrees -D language=en . $READTHEDOCS_OUTPUT/html
⋮
Configuration error:
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/sphinxcontrib-cadquery/envs/39/lib/python3.9/site-packages/sphinx/config.py", line 350, in eval_config_file
    exec(code, namespace)
  File "/home/docs/checkouts/readthedocs.org/user_builds/sphinxcontrib-cadquery/checkouts/39/docs/conf.py", line 7, in <module>
    import sphinxcontrib.cadquery
ModuleNotFoundError: No module named 'sphinxcontrib.cadquery'
```

When added to `.readthedocs.yaml`: `build.jobs.post-install` the following also fails:

```
python -c "import sphinxcontrib.cadquery; print(sphinxcontrib.cadquery.__version__)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'sphinxcontrib.cadquery'
```

Last successful build: [Build #19376393](https://readthedocs.org/projects/sphinxcontrib-cadquery/builds/19376393/) dated Feb. 4, 2023. 1:54 a.m.
First failed build: [Build #19562383](https://readthedocs.org/projects/sphinxcontrib-cadquery/builds/19562383/) dated Feb. 22, 2023. 9:39 a.m.

The `poetry install` command reports successful installation of the project package:

```
poetry install
⋮
Installing the current project: sphinxcontrib-cadquery (0.4.0)
```

Dependencies installed with `poetry install` are available for import e.g `cadquery`, just not the current (root) project.

**Comment by sethfischer** [comment]
readthedocs/readthedocs.org#10058
